// Generated by CoffeeScript 1.4.0
(function() {
  var render;

  render = require('./controller-helper.js').render;

  module.exports = function(app) {
    return app.get('/', function(req, res) {
      var viewData;
      viewData = {
        title: 'PLANSQUARE',
        bootstrap: {
          view: 'index',
          data: {
            events: [
              {
                title: 'NodeConf 2013',
                start: '6-27-13',
                end: '6-30-13',
                type: 'coding'
              }, {
                title: 'Enlightened Society Assembly',
                start: '7-6-13',
                end: '7-21-13',
                type: 'meditation'
              }, {
                title: 'Buddhist Geeks 2013',
                start: '8-16-13',
                end: '8-18-13',
                type: 'meditation'
              }
            ]
          }
        }
      };
      return render(req, res, viewData);
    });
  };

}).call(this);
